/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import javax.swing.JOptionPane;
import controller.ManipulaDados;
import java.awt.BorderLayout;
import javax.swing.JButton;
import models.Graficos;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author djairtb
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaPrincipal
     * @param registraLixo
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JTabbedPane();
        telaPorTipo = new javax.swing.JPanel();
        pnGraficoTipo = new javax.swing.JPanel();
        telaPorEstado = new javax.swing.JPanel();
        pnGraficoEstado = new javax.swing.JPanel();
        telaPorDia = new javax.swing.JPanel();
        registrarInformacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        pnGraficoTipo.setBackground(new java.awt.Color(102, 102, 255));
        pnGraficoTipo.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout telaPorTipoLayout = new javax.swing.GroupLayout(telaPorTipo);
        telaPorTipo.setLayout(telaPorTipoLayout);
        telaPorTipoLayout.setHorizontalGroup(
            telaPorTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaPorTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnGraficoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        telaPorTipoLayout.setVerticalGroup(
            telaPorTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPorTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnGraficoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        painelPrincipal.addTab("POR TIPO", telaPorTipo);

        pnGraficoEstado.setBackground(new java.awt.Color(255, 153, 0));
        pnGraficoEstado.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout telaPorEstadoLayout = new javax.swing.GroupLayout(telaPorEstado);
        telaPorEstado.setLayout(telaPorEstadoLayout);
        telaPorEstadoLayout.setHorizontalGroup(
            telaPorEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPorEstadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnGraficoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        telaPorEstadoLayout.setVerticalGroup(
            telaPorEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPorEstadoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pnGraficoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        painelPrincipal.addTab("POR ESTADO", telaPorEstado);

        javax.swing.GroupLayout telaPorDiaLayout = new javax.swing.GroupLayout(telaPorDia);
        telaPorDia.setLayout(telaPorDiaLayout);
        telaPorDiaLayout.setHorizontalGroup(
            telaPorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        telaPorDiaLayout.setVerticalGroup(
            telaPorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        painelPrincipal.addTab("POR DIA", telaPorDia);

        registrarInformacoes.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        registrarInformacoes.setText("REGISTRAR INFORMAÇÕES DO DIA");
        registrarInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarInformacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelPrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(registrarInformacoes)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrarInformacoes)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        painelPrincipal.getAccessibleContext().setAccessibleName("Por Dia");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarInformacoesActionPerformed
        TelaCadastro telaCadastro = new TelaCadastro(pnGraficoTipo);
        telaCadastro.setVisible(true);
        
    }//GEN-LAST:event_registrarInformacoesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    
    public JButton getRegistrarInformacoes() {
        return registrarInformacoes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane painelPrincipal;
    private javax.swing.JPanel pnGraficoEstado;
    private javax.swing.JPanel pnGraficoTipo;
    private javax.swing.JButton registrarInformacoes;
    private javax.swing.JPanel telaPorDia;
    private javax.swing.JPanel telaPorEstado;
    private javax.swing.JPanel telaPorTipo;
    // End of variables declaration//GEN-END:variables
}
